if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT are required")
endif()

file(READ "${INPUT}" corpus_hex HEX)
file(WRITE "${OUTPUT}" "/* Generated from the bundled corpus. */\nstatic const char *const tarpit_embedded_hex[] = {\n")
string(LENGTH "${corpus_hex}" hex_length)
set(offset 0)
while(offset LESS hex_length)
    math(EXPR remaining "${hex_length} - ${offset}")
    if(remaining GREATER 96)
        set(count 96)
    else()
        set(count ${remaining})
    endif()
    string(SUBSTRING "${corpus_hex}" ${offset} ${count} chunk)
    file(APPEND "${OUTPUT}" "    \"${chunk}\",\n")
    math(EXPR offset "${offset} + ${count}")
endwhile()
file(APPEND "${OUTPUT}" "};\n")
